export const ceramicMugsAndFlasks = [
    {
        id: 1,
        name: "Chuck",
        price: 20.99,
        description: "A handmade ceramic mug featuring a unique design.",
        imageUrl: "/images/Chuck.jpg",
    },
    {
        id: 2,
        name: "Flaskie",
        price: 15.99,
        description: "A handmade ceramic flask with a sleek and modern design.",
        imageUrl: "/images/Flaskie.jpg",
    },
    {
        id: 3,
        name: "MacSmithPlatter",
        price: 35.99,
        description: "A handmade ceramic platter with a unique design.",
        imageUrl: "/images/MacSmithPlatter.jpg",
    },
    {
        id: 4,
        name: "birdPlatter",
        price: 30.99,
        description: "A handmade ceramic platter featuring a bird design.",
        imageUrl: "/images/birdPlatter.jpg",
    },
    {
        id: 5,
        name: "celadon",
        price: 25.99,
        description: "A handmade ceramic mug in a celadon glaze.",
        imageUrl: "/images/celadon.jpg",
    },
    {
        id: 6,
        name: "dots",
        price: 22.99,
        description: "A handmade ceramic mug with a dot design.",
        imageUrl: "/images/dots.jpg",
    },
    {
        id: 7,
        name: "dougMug",
        price: 18.99,
        description: "A handmade ceramic mug with a unique design.",
        imageUrl: "/images/dougMug.jpg",
    },
    {
        id: 8,
        name: "drip",
        price: 19.99,
        description: "A handmade ceramic mug with a drip design.",
        imageUrl: "/images/drip.jpg",
    },
    {
        id: 9,
        name: "eyeFlask",
        price: 17.99,
        description: "A handmade ceramic flask with an eye design.",
        imageUrl: "/images/eyeFlask.jpg",
    },
    {
        id: 10,
        name: "greenheckPlatter",
        price: 32.99,
        description: "A handmade ceramic platter with a unique design.",
        imageUrl: "/images/greenheckPlatter.jpg",
    },
    {
        id: 11,
        name: "hands",
        price: 24.99,
        description: "A handmade ceramic mug with a hand design.",
        imageUrl: "/images/hands.jpg",
    },
    {
        id: 12,
        name: "longcup",
        price: 21.99,
        description: "A handmade ceramic mug in a long design.",
        imageUrl: "/images/longcup.jpg",
    },
    {
        id: 13,
        name: "longflask",
        price: 16.99,
        description: "A handmade ceramic flask in a long design.",
        imageUrl: "/images/longflask.jpg",
    },
    {
        id: 14,
        name: "lyon",
        price: 23.99,
        description: "A handmade ceramic mug with a unique design.",
        imageUrl: "/images/lyon.jpg",
    },
    {
        id: 15,
        name: "martyPlatter",
        price: 33.99,
        description: "A handmade ceramic platter with a unique design.",
        imageUrl: "/images/martyPlatter.jpg",
    },
    {
        id: 16,
        name: "shell",
        price: 29.99,
        description: "A handmade ceramic mug with a shell design.",
        imageUrl: "/images/shell.jpg",
    },
    {
        id: 17,
        name: "swirlyMug",
        price: 19.99,
        description: "A handmade ceramic mug with a swirly design.",
        imageUrl: "/images/swirlyMug.jpg",
    },
]
